### Шаг 1: Первый запрос (создаем сессию)
POST http://127.0.0.1:8000/chat-about-job/stream
Content-Type: application/json

{
  "message": "Привет! Я Junior Python Developer, знаю FastAPI и Docker. Запомни это."
}

### После выполнения возьми x-session-id из Headers ответа

### Шаг 2: Второй запрос (проверка памяти)
POST http://127.0.0.1:8000/chat-about-job/stream
Content-Type: application/json

{
  "message": "Какие технологии я перечислил в прошлом сообщении?",
  "session_id": "9fce0118-07ff-4731-be6c-e66c50a17ad5"
}